### ISSUE TITLE
Smartcards with SafeSign Applet

### ISSUE THREAD

**Issue by brunopacola** [ea/smartcard-sniffer#1]
Hello!

I have smartcards that use the SafeSign applet.

With smartcard-sniffer I can find any ADPU command used for each smartcard?

SafeSign A.E.T: http://www.aeteurope.nl/en/pub/products/safesign.cfm

**Comment by ea** [comment]
If the middleware/minidriver for these cards uses winscard to communicate with the card, yes. You will be able to capture the raw bytes sent and received to/from the card. Then, armed with APDU info and codes from the manual/ISO standard, you can see what's going on.

**Comment by brunopacola** [comment]
Thank you! =)
